package org.example.mediaserver.mappers;

import org.example.mediaserver.dao.entities.VideoEntity;
import org.springframework.stereotype.Component;
import org.example.proto.Video;
import org.example.proto.UploadVideoRequest;

// Mapper component for bidirectional conversion between Video entities and Protocol Buffer messages
// Handles transformation: Proto messages <-> JPA database entities
@Component
public class VideoMapper {

    /**
     * Convert Protocol Buffer upload request to JPA entity
     * Maps all video fields from the gRPC request to database entity
     * Note: ID field is auto-generated by database, not set manually
     *
     * @param request The gRPC upload request containing video data
     * @return VideoEntity ready for database persistence
     */
    public VideoEntity fromUploadRequestToEntity(UploadVideoRequest request) {
        VideoEntity entity = new VideoEntity();
        // Extract and set basic video information
        entity.setTitle(request.getTitle());
        entity.setDescription(request.getDescription());
        entity.setUrl(request.getUrl());
        entity.setDurationSeconds(request.getDurationSeconds());
        // Note: Primary key (ID) will be automatically generated by JPA
        // Creator association is handled separately in the service layer
        return entity;
    }

    /**
     * Transform JPA entity to Protocol Buffer message format
     * Converts database entity to gRPC-compatible message structure
     * Includes nested creator information
     * 
     * @param entity The video entity from database
     * @return Video protobuf message ready for gRPC transmission
     */
    public Video fromEntityToProto(VideoEntity entity) {
        // Build the protobuf Video message using builder pattern
        return Video.newBuilder()
                .setId(String.valueOf(entity.getId()))
                .setTitle(entity.getTitle())
                .setDescription(entity.getDescription())
                .setUrl(entity.getUrl())
                .setDurationSeconds(entity.getDurationSeconds())
                // Embed creator information as a nested message
                .setCreator(org.example.proto.Creator.newBuilder()
                        .setId(String.valueOf(entity.getCreator().getId()))
                        .setName(entity.getCreator().getName())
                        .setEmail(entity.getCreator().getEmail())
                        .build())
                .build();
    }
}